name: Docker Image Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push_image:
    permissions:
        contents: read
        packages: write
    uses: Unicycle-Unicorn/CICD/.github/workflows/docker-build-push.yml@main
    with:
      subdirectory: 'Notes Application'
