name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: /app
    - name: Build the Docker image
      working-directory: /app
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: Install doctl 
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
    - name: Log in to DO Container Registry 
      run: doctl registry login --expiry-seconds 600
    - name: Push image to DO Container Registry 
      run: docker push ${{ env.DIGITALOCEAN_REGISTRY }}/my-image-name:latest
