name: Docker Image Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    env:
        PROJECT_DIRECTORY: 'Notes Application'
        IMAGE_NAME: 'some-name'
    permissions:
        contents: read
        packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image
      working-directory: ${{ github.workspace }}/${{ env.PROJECT_DIRECTORY }}
      run: docker build . --tag ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker Image
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
