name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
        contents: read
        packages: write
    env:
        PROJECT_DIRECTORY: 'Notes Application'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: ${{ github.workspace }}/${{ env.PROJECT_DIRECTORY }}
      run: docker build . --tag ghcr.io/unicycle-unicorn/image-name:latest
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image to DO Container Registry 
      run: docker push ghcr.io/unicycle-unicorn/image-name:latest
